project:
  type: website
  output-dir: docs

website:
  title: "visualcve"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cna_affected.qmd
        text: cna.affected
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

